name: dl
channels:
- defaults
- soumith
dependencies:
- conda=4.6.14
- pip=19.0.3
- python=3.7
- tqdm=4.31.1
- pip:
  - chainer==3.0.0
  - https://cntk.ai/PythonWheel/CPU-Only/cntk-2.7.post1-cp27-cp27m-win_amd64.whl
  - keras==2.0.9
  - mxnet==0.12.0
  - tensorflow==1.4.0
  - https://download.pytorch.org/whl/cpu/torch-1.1.0-cp37-cp37m-win_amd64.whl
